Chengdexy.CN/Controllers/BlogsController.cs
using Chengdexy.CN.DAL;
using Chengdexy.CN.Models;
using Chengdexy.CN.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chengdexy.CN.Controllers
{
    public class BlogsController : Controller
    {
        private MainContext db = new MainContext();

        // GET: Blogs
        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public ActionResult ShowNavbar()
        {
            var itemList = db.NavbarItems.ToList();

            return PartialView("~/Views/Shared/_PartialNavbar.cshtml", new NavbarItemVM(itemList, 3));
        }
    }
}

Chengdexy.CN/Controllers/ShowController.cs
using Chengdexy.CN.DAL;
using Chengdexy.CN.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chengdexy.CN.Controllers
{
    public class ShowController : Controller
    {
        private MainContext db = new MainContext();

        // GET: Show
        public ActionResult Index(int ID = 1)
        {
            var blogPage = db.BlogPages.ToList().Where(bp => (bp.ID == ID)).FirstOrDefault();
            if (blogPage==null)
            {
                blogPage = new BlogPage();
            }
            return View(blogPage);
        }
    }
}

Chengdexy.CN/Views/Show/Index.cshtml
@model Chengdexy.CN.Models.BlogPage
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Action("ShowNavbar","Blogs")
<!--内容部分-->
<link href="~/CSS/editormd.css" rel="stylesheet" />
<script src="~/lib/marked.min.js"></script>
<script src="~/lib/prettify.min.js"></script>
<script src="~/lib/raphael.min.js"></script>
<script src="~/lib/underscore.min.js"></script>
<script src="~/lib/sequence-diagram.min.js"></script>
<script src="~/lib/flowchart.min.js"></script>
<script src="~/lib/jquery.flowchart.min.js"></script>
<script src="~/JS/editormd.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        var wordsView;
        wordsView = editormd.markdownToHTML("showMD", {
            htmlDecode      : false,  // you can filter tags decode
            emoji           : true,
            taskList        : true
        });

    })
</script>
<div class="content">
    @*<h1>@Model.Title<br /><small class="pull-right">@Model.CreateTime.ToString("yyyy年MM月dd日")</small></h1>
    <hr />
    <blockquote>
        <p>@Model.Sketch</p>
    </blockquote>*@
    <div id="showMD">
        <textarea style="display:none;" name="editormd-markdown-doc">@Model.Content</textarea>
    </div>
</div>

<!--内容部分结束-->
<a href="#top" class="btn btn-default btn-sm pull-right">返回顶部</a>