Chengdexy.CN/Controllers/ShowController.cs
using Chengdexy.CN.DAL;
using Chengdexy.CN.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chengdexy.CN.Controllers
{
    public class ShowController : Controller
    {
        private MainContext db = new MainContext();

        // GET: Show
        public ActionResult Index(int ID = 1)
        {
            var blogPage = db.BlogPages.ToList().Where(bp => (bp.ID == ID)).FirstOrDefault();
            if (blogPage==null)
            {
                blogPage = new BlogPage();
            }
            return View(blogPage);
        }
    }
}

Chengdexy.CN/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>@Html.Action("SetSiteTitle", "Global")</title>
    <link rel="stylesheet" href="~/CSS/bootstrap.min.css">
    <link rel="shortcut icon" href="favicon.ico" />
    <style type="text/css">
        body {
            font-family: "微软雅黑";
            background-color: silver;
        }

        .container {
            background-color: white;
        }

        .text-indent {
            text-indent: 2em;
        }

        .cut {
            /*text-overflow: -o-ellipsis-lastline;*/
            overflow: hidden;
            text-overflow: ellipsis;
            display: -webkit-box;
            -webkit-line-clamp: 3;
            -webkit-box-orient: vertical;
        }
    </style>
</head>

<body>
    <script src="~/JS/jquery.js"></script>
    <script src="~/JS/bootstrap.min.js"></script>
    <div class="container col-sm-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <!--头部-->
        <div class="page-header">
            <h1>
                @Html.Action("SetSiteMainCapital", "Global")
                <small>@Html.Action("SetSiteSubCapital","Global")</small>
            </h1>
        </div>
        
        <br />
        <div>
            @RenderBody()
        </div>
    </div>
    <footer class="text-center">
        <div class="container col-sm-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
            <hr />
            <p class="text-center">Built by <a href="mailto:chengdexy@sina.com">@@Chengdexy</a>, February 15, 2017.</p>
            <br />
        </div>
    </footer>
</body>
</html>

Chengdexy.CN/Views/Shared/_LayoutAdmin.cshtml
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Admin Space : Chengdexy.Cn</title>
    <link rel="stylesheet" type="text/css" href="~/CSS/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/CSS/base.css" />
    <link rel="stylesheet" type="text/css" href="~/CSS/uppreview.css" />
    <style type="text/css">
        body {
            font-family: "微软雅黑";
        }
    </style>
</head>

<body>
    <script src="~/JS/jquery.js" type="text/javascript" charset="utf-8"></script>
    <div class="container">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Chengdexy.CN</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Home")">Chengdexy.CN</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                @*这里是主导航topbar*@
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="@Url.Action("Logout","Login")">Log Out</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Home")">Back Home</a>
                    </li>
                    <li>
                        <a href="#"></a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row">
                @RenderBody()
            </div>
        </div>
    </div>

    <!--js-->
    <script src="~/Scripts/jquery.unobtrusive-ajax.js" type="text/javascript" charset="utf-8"></script>
    <script src="~/JS/bootstrap.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="~/JS/uppreview.js" type="text/javascript" charset="utf-8"></script>
</body>

</html>

Chengdexy.CN/Views/Shared/_PartialAdminSidebar.cshtml
@model Chengdexy.CN.ViewModels.SidebarItemVM

<div class="col-sm-3 col-md-2 sidebar">
    <ul class="nav nav-sidebar">
        @for (int i = 0; i < Model.SidebarItems.Count; i++)
        {
            string active = string.Empty;
            if (Model.ActiveIndex == i + 1)
            {
                active = "active";
            }
            <li class="@active">
                @Html.ActionLink(Model.SidebarItems[i].Text, Model.SidebarItems[i].Action, Model.SidebarItems[i].Controller)
            </li>
        }
    </ul>
</div>

Chengdexy.CN/Views/Shared/_PartialJumbotron.cshtml
@model Chengdexy.CN.Models.Jumbotron
<!--巨幕-->
@if (Model != null)
{
    <div class="jumbotron">
        <h1>@Model.Capital</h1>
        <p>@Model.Describe</p>
        <p>
            <a class="btn btn-primary btn-lg" href="@Model.DownloadUrl">@Model.DownloadButtonText</a>
        </p>
    </div>
}

Chengdexy.CN/Views/Shared/_PartialNavbar.cshtml
@model Chengdexy.CN.ViewModels.NavbarItemVM
<!--主导航-->
<div>
    <ul class="nav nav-tabs">
        @for (int i = 0; i < Model.NavbarItems.Count; i++)
        {
            string active = string.Empty;
            if (Model.ActiveIndex == i + 1)
            {
                active = "active";
            }
                <li role="presentation" class="@active">
                    @Html.ActionLink(Model.NavbarItems[i].Text, Model.NavbarItems[i].Action, Model.NavbarItems[i].Route)
                </li>
        }
    </ul>
</div>

Chengdexy.CN/Views/Shared/_PartialProgramList.cshtml
@model List<Chengdexy.CN.Models.Program>

@foreach (var program in Model)
{
    <div class="panel panel-default">
        <!--Default panel contents-->
        <div class="panel-heading"><big><b><i>@program.Ename</i></b></big>&nbsp;<small>@program.Cname</small> </div>
        <div class="panel-body">
            <p class="text-muted"><i>@program.Motive</i></p>
            <strong>@program.Ename 目前支持</strong>
            <div>
                <ul>
                    @{
                        string[] describes = program.Describe.Replace("\r\n", "\n").Split('\n');
                        for (int i = 0; i < describes.Length; i++)
                        {
                            if (!string.IsNullOrEmpty(describes[i]))
                            {
                                <li>@describes[i]</li>
                            }
                        }
                    }
                </ul>
            </div>
        </div>
        <!--Table-->
        <table class="table text-center">
            @foreach (var edition in program.ProgramEditions)
            {
                <tr>
                    <td>@edition.PublishDate.ToString("yyyy-MM-dd")</td>
                    <td class="text-left"><i>@program.Ename @edition.EditionString</i></td>
                    <td>
                        <a class="btn btn-default btn-sm" href="@edition.DownloadUrl">下载</a>
                    </td>
                </tr>
            }

        </table>
    </div>
                    }

Chengdexy.CN/Views/Shared/_PartialSketchList.cshtml
@model List<Chengdexy.CN.ViewModels.BlogSketchVM>

<!--内容列表-->
<div class="row">
    @*
        1. lg屏:每行2项,col-lg-6,图片3文字9按钮2后退9
        2. md屏:每行1项,col-md-12,图片2文字10按钮2后退9
        3. sm屏:每行1项,col-sm-12,图片3文字9按钮2后退9
        4. xs屏:每行1项,col-xs-12,图片隐藏文字12按钮3后退9
    *@
    @for (int i = 0; i < Model.Count; i++)
    {
        //内容列表项开始
        var mod = Model[i];
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6" style="height:10em;">
            <div class="hidden-xs col-sm-3  col-md-2 col-lg-3">
                <a href="#" class="thumbnail"><img src="@mod.BlogPageImagePath" alt="" /></a>
            </div>
            <div class="col-xs-12  col-sm-9 col-md-10 col-lg-9">
                <h3><a href="@Url.Action("Index","Show", new { ID = mod.BlogPageId })" style="color:black;">@mod.BlogPageTitle</a></h3>
                <p class="text-muted cut">@mod.BlogPageSketch</p>
                @*<a href="@Url.Action("Index","Show", new { ID = mod.BlogPageId })" class="btn btn-default col-xs-3 col-xs-offset-9 col-sm-2 com-sm-offset-9 col-md-2 col-md-offset-9">详情...</a>*@
            </div>
        </div>
        //列表项结束
    }

</div>